name: Publish

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Build Linux packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF}" == "refs/heads/main" && "${GITHUB_REPOSITORY_OWNER}" == "electron-react-boilerplate" ]]; then
            npm exec electron-builder -- --publish always --linux
          else
            npm exec electron-builder -- --publish never --linux
          fi

      - name: Upload Linux build artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-${{ github.run_number }}
          path: release/build/*
          if-no-files-found: error
