name: Publish

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Build Linux artifacts (PR validation)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec electron-builder -- --linux --publish never

      - name: Publish Linux releases
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository_owner == 'electron-react-boilerplate' }}
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --linux
